name: MLOps 2022/2023 Docker Images CI
on:
  push:
    branches: [ "api/github_action" ]
jobs:
  build_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:  quay.io/yourquayaccount/mlops_python_2022_2023:1.0.0,quay.io/yourquayaccount/mlops_python_2022_2023:latest